plugin:
  webapp: no
  static: no
  description: |
    Work in progress !
  dependencies:
    - pyquery
channels_params:
  question:
    name: 'Survey question'
    placeholder: 'Question'
    type: string
    default: 'Aimez-vous la pluie ?'
  author:
     name: 'Signature'
     placeholder: 'Signature'
     type: string
     default: 'Signé : ICTEAM'
  answers:
     name: 'Answers'
     placeholder: 'Answer'
     type: list[string]
     default: ['Oui', 'Non']
     add: 'Add answer (5 max.)'
  #Idée : laisser la possibilité d'entrer 4 réponses et si vide pas afficher
  secret:
    name: 'Survey results are secret'
    type: bool
    default: no
